<?php
return [
    ["id" => 1, "level" => "1", "parent_task_id" => null, "name" => "Engineering & Design", "weight" => "10.00", "sub_tasks_count" => "4", "sub_tasks_weight_sum" => "100.00"],
    ["id" => 2, "level" => "2", "parent_task_id" => 1, "name" => "GENERAL", "weight" => "24.00", "sub_tasks_count" => "6", "sub_tasks_weight_sum" => "24.00"],
    ["id" => 3, "level" => "3", "parent_task_id" => 2, "name" => "GENERAL ARRANGEMENT", "weight" => "5.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 4, "level" => "3", "parent_task_id" => 2, "name" => "LINES PLAN", "weight" => "5.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 5, "level" => "3", "parent_task_id" => 2, "name" => "DRAFT & ZINC ANODE ARRANGEMENT", "weight" => "5.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 6, "level" => "3", "parent_task_id" => 2, "name" => "SIDEBOARD", "weight" => "3.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 7, "level" => "3", "parent_task_id" => 2, "name" => "WELDING SCHEDULE", "weight" => "3.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 8, "level" => "3", "parent_task_id" => 2, "name" => "BOLLARD ARRANGEMENT", "weight" => "3.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 9, "level" => "2", "parent_task_id" => 1, "name" => "HULL", "weight" => "36.00", "sub_tasks_count" => "10", "sub_tasks_weight_sum" => "36.00"],
    ["id" => 10, "level" => "3", "parent_task_id" => 9, "name" => "BHD'S & FRAME SECTION", "weight" => "5.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 11, "level" => "3", "parent_task_id" => 9, "name" => "STRUCTURAL PROFILE & DECK", "weight" => "5.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 12, "level" => "3", "parent_task_id" => 9, "name" => "SHELL EXPANSION", "weight" => "5.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 13, "level" => "3", "parent_task_id" => 9, "name" => "CONTRUCTION DETAIL", "weight" => "5.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 14, "level" => "3", "parent_task_id" => 9, "name" => "NDT PLAN", "weight" => "3.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 15, "level" => "3", "parent_task_id" => 9, "name" => "MANHOLE", "weight" => "3.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 16, "level" => "3", "parent_task_id" => 9, "name" => "SKEG CONTRUCTION", "weight" => "2.50", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 17, "level" => "3", "parent_task_id" => 9, "name" => "WINCH HOUSE SECURING DIVICE", "weight" => "2.50", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 18, "level" => "3", "parent_task_id" => 9, "name" => "WINCH HOUSE", "weight" => "2.50", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 19, "level" => "3", "parent_task_id" => 9, "name" => "BULWARK", "weight" => "2.50", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 20, "level" => "2", "parent_task_id" => 1, "name" => "OUTFITTING", "weight" => "14.00", "sub_tasks_count" => "7", "sub_tasks_weight_sum" => "14.00"],
    ["id" => 21, "level" => "3", "parent_task_id" => 20, "name" => "BOLLARD DETAIL", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 22, "level" => "3", "parent_task_id" => 20, "name" => "TOWING BRACKET DETAIL", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 23, "level" => "3", "parent_task_id" => 20, "name" => "ANCHOR SEATING", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 24, "level" => "3", "parent_task_id" => 20, "name" => "SIDEBOARD DOOR", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 25, "level" => "3", "parent_task_id" => 20, "name" => "VERTICAL LADDER", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 26, "level" => "3", "parent_task_id" => 20, "name" => "WINCH HOUSE STAIR ", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 27, "level" => "3", "parent_task_id" => 20, "name" => "WINCH HOUSE LAMP DETAIL", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 28, "level" => "2", "parent_task_id" => 1, "name" => "PRODUCTION HULL", "weight" => "26.00", "sub_tasks_count" => "1", "sub_tasks_weight_sum" => "2.00"],
    ["id" => 29, "level" => "3", "parent_task_id" => 28, "name" => "ASSEMBLY PLAN", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 30, "level" => "3", "parent_task_id" => 31, "name" => "WEB CUTTING PLAN", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 31, "level" => "3", "parent_task_id" => 31, "name" => "BTM SEAM ARRANGEMENT/DETAILS", "weight" => "2.00", "sub_tasks_count" => "16", "sub_tasks_weight_sum" => "24.00"],
    ["id" => 32, "level" => "3", "parent_task_id" => 31, "name" => "DECK SEAM ARRANGEMENT/DETAILS", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 33, "level" => "3", "parent_task_id" => 31, "name" => "S/S SEAM ARRANGEMENT/DETAILS", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 34, "level" => "3", "parent_task_id" => 31, "name" => "L/BHD SEAM ARRANGEMENT/DETAILS", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 35, "level" => "3", "parent_task_id" => 31, "name" => "T/BHD SEAM ARRANGEMENT/DETAILS", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 36, "level" => "3", "parent_task_id" => 31, "name" => "BRACKET DETAIL", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 37, "level" => "3", "parent_task_id" => 31, "name" => "NESTING BRACKET", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 38, "level" => "3", "parent_task_id" => 31, "name" => "SKEG", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 39, "level" => "3", "parent_task_id" => 31, "name" => "SIDEBOARD & DOOR", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 40, "level" => "3", "parent_task_id" => 31, "name" => "RING MANHOLE", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 41, "level" => "3", "parent_task_id" => 31, "name" => "BOX FENDER", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 42, "level" => "3", "parent_task_id" => 31, "name" => "VERTICAL LADDER", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 43, "level" => "3", "parent_task_id" => 31, "name" => "WINCH HOUSE", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 44, "level" => "3", "parent_task_id" => 31, "name" => "BULWARK", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 45, "level" => "3", "parent_task_id" => 31, "name" => "GUNWALE", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 46, "level" => "1", "parent_task_id" => null, "name" => "Procurement", "weight" => "30.00", "sub_tasks_count" => "3", "sub_tasks_weight_sum" => "81.00"],
    ["id" => 47, "level" => "2", "parent_task_id" => 46, "name" => "Material & Consumable", "weight" => "75.00", "sub_tasks_count" => "4", "sub_tasks_weight_sum" => "75.00"],
    ["id" => 48, "level" => "3", "parent_task_id" => 47, "name" => "Steel Plate", "weight" => "40.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 49, "level" => "3", "parent_task_id" => 47, "name" => "Profiles/Angle. Beams", "weight" => "20.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 50, "level" => "3", "parent_task_id" => 47, "name" => "Consumable (W. Rod. etc.)", "weight" => "5.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 51, "level" => "3", "parent_task_id" => 47, "name" => "Paint ", "weight" => "10.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 52, "level" => "2", "parent_task_id" => 46, "name" => "Mooring & Deck Equipment", "weight" => "2.00", "sub_tasks_count" => "4", "sub_tasks_weight_sum" => "21.00"],
    ["id" => 53, "level" => "3", "parent_task_id" => 52, "name" => "Anchor & Chain. shackle. Chain Stopper etc.", "weight" => "5.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 54, "level" => "3", "parent_task_id" => 52, "name" => "Anchor Windlass ", "weight" => "10.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 55, "level" => "3", "parent_task_id" => 52, "name" => "PPC Ropes", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 56, "level" => "3", "parent_task_id" => 52, "name" => "Towing Equipment (shackel. chain & wire)", "weight" => "4.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 57, "level" => "2", "parent_task_id" => 46, "name" => "Fitting & Accessories", "weight" => "4.00", "sub_tasks_count" => "3", "sub_tasks_weight_sum" => "4.00"],
    ["id" => 58, "level" => "3", "parent_task_id" => 57, "name" => "Cathodic Protection", "weight" => "2.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 59, "level" => "3", "parent_task_id" => 57, "name" => "Navigation Light", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 60, "level" => "3", "parent_task_id" => 57, "name" => "Tyre Fender", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 61, "level" => "1", "parent_task_id" => null, "name" => "Preparation & General", "weight" => "30.00", "sub_tasks_count" => "5", "sub_tasks_weight_sum" => "100.00"],
    ["id" => 62, "level" => "2", "parent_task_id" => 61, "name" => "STEEL CUTTING", "weight" => "10", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 63, "level" => "2", "parent_task_id" => 61, "name" => "KEEL LAYING", "weight" => "35", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 64, "level" => "2", "parent_task_id" => 61, "name" => "LAUNCHING", "weight" => "20", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 65, "level" => "2", "parent_task_id" => 61, "name" => "SERTIFICATE ", "weight" => "20", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 66, "level" => "2", "parent_task_id" => 61, "name" => "DELIVERY", "weight" => "15", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 67, "level" => "1", "parent_task_id" => null, "name" => "Hull Construction", "weight" => "30.00", "sub_tasks_count" => "29", "sub_tasks_weight_sum" => "300.00"],
    ["id" => 68, "level" => "2", "parent_task_id" => 67, "name" => "BOTTOM SHELL", "weight" => "25.20", "sub_tasks_count" => "24", "sub_tasks_weight_sum" => "25.20"],
    ["id" => 69, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 0-4 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 70, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 0-4 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 71, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 0-4 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 72, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 4-7 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 73, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 4-7 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 74, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 4-7 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 75, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 7-10 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 76, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 7-10 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 77, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 7-10 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 78, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 10-13 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 79, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 10-13 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 80, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 10-13 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 81, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 13-16 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 82, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 13-16 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 83, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 13-16 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 84, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 16-19 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 85, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 16-19 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 86, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 16-19 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 87, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 19-22 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 88, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 19-22 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 89, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 19-22 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 90, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 22-25 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 91, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 22-25 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 92, "level" => "3", "parent_task_id" => 68, "name" => "BTM FR. 22-25 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 93, "level" => "2", "parent_task_id" => 67, "name" => "TRANSV. BHD", "weight" => "18.30", "sub_tasks_count" => "19", "sub_tasks_weight_sum" => "18.30"],
    ["id" => 94, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 4 (Full Set)", "weight" => "2.10", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 95, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 7 (P)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 96, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 7 (C)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 97, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 7 (S)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 98, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 10 (P)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 99, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 10 (C)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 100, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 10 (S)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 101, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 13 (P)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 102, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 13 (C)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 103, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 13 (S)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 104, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 16 (P)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 105, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 16 (C)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 106, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 16 (S)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 107, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 19 (P)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 108, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 19 (C)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 109, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 19 (S)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 110, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 22 (P)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 111, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 22 (C)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 112, "level" => "3", "parent_task_id" => 93, "name" => "Transv. BHD Fr. 22 (S)", "weight" => "0.90", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 113, "level" => "2", "parent_task_id" => 67, "name" => "LONG BHD", "weight" => "8.40", "sub_tasks_count" => "6", "sub_tasks_weight_sum" => "8.40"],
    ["id" => 114, "level" => "3", "parent_task_id" => 113, "name" => "Long. BHD Fr. 0 - Fr. 13 (P)", "weight" => "1.85", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 115, "level" => "3", "parent_task_id" => 113, "name" => "Long. BHD Fr. 13 - Fr. 22 (P)", "weight" => "1.85", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 116, "level" => "3", "parent_task_id" => 113, "name" => "Long. BHD Fr. 22 - Fr. 25 (P) ", "weight" => "0.50", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 117, "level" => "3", "parent_task_id" => 113, "name" => "Long. BHD Fr. 0 - Fr. 13 (S)", "weight" => "1.85", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 118, "level" => "3", "parent_task_id" => 113, "name" => "Long. BHD Fr. 13 - Fr. 22 (S)", "weight" => "1.85", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 119, "level" => "3", "parent_task_id" => 113, "name" => "Long. BHD Fr. 22 - Fr. 25 (S) ", "weight" => "0.50", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 120, "level" => "2", "parent_task_id" => 67, "name" => "SIDE SHELL", "weight" => "8.40", "sub_tasks_count" => "6", "sub_tasks_weight_sum" => "8.40"],
    ["id" => 121, "level" => "3", "parent_task_id" => 120, "name" => "Side Shell Fr. 0 - Fr. 13 (P)", "weight" => "1.85", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 122, "level" => "3", "parent_task_id" => 120, "name" => "Side Shell Fr. 13 - Fr. 22 (P)", "weight" => "1.85", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 123, "level" => "3", "parent_task_id" => 120, "name" => "Side Shell Fr. 25 - Fr. 25 (P)", "weight" => "0.50", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 124, "level" => "3", "parent_task_id" => 120, "name" => "Side Shell Fr. 0 - Fr. 13 (S)", "weight" => "1.85", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 125, "level" => "3", "parent_task_id" => 120, "name" => "Side Shell Fr. 13 - Fr. 22 (S)", "weight" => "1.85", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 126, "level" => "3", "parent_task_id" => 120, "name" => "Side Shell Fr. 25 - Fr. 25 (S)", "weight" => "0.50", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 127, "level" => "2", "parent_task_id" => 67, "name" => "MAIN DECK", "weight" => "25.20", "sub_tasks_count" => "24", "sub_tasks_weight_sum" => "25.20"],
    ["id" => 128, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.0 - Fr.4 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 129, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.0 - Fr.4 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 130, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.0 - Fr.4 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 131, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.4 - Fr.7 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 132, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.4 - Fr.7 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 133, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.4 - Fr.7 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 134, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.7 - Fr.10 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 135, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.7 - Fr.10 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 136, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.7 - Fr.10 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 137, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.10 - Fr.13 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 138, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.10 - Fr.13 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 139, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.10 - Fr.13 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 140, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.13 - Fr.16 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 141, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.13 - Fr.16 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 142, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.13 - Fr.16 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 143, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.16 - Fr.19 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 144, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.16 - Fr.19 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 145, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.16 - Fr.19 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 146, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.19 - Fr.22 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 147, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.19 - Fr.22 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 148, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.19 - Fr.22 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 149, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.22 - Fr.25 (P)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 150, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.22 - Fr.25 (C)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 151, "level" => "3", "parent_task_id" => 127, "name" => "Main Deck Fr.22 - Fr.25 (S)", "weight" => "1.05", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 152, "level" => "2", "parent_task_id" => 67, "name" => "HEAD LOCK", "weight" => "5.00", "sub_tasks_count" => "5", "sub_tasks_weight_sum" => "5.00"],
    ["id" => 153, "level" => "3", "parent_task_id" => 152, "name" => "Main Deck Fr. 25 - Fr. 29", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 154, "level" => "3", "parent_task_id" => 152, "name" => "Transv. BHD Fr.25 (Full Set)", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 155, "level" => "3", "parent_task_id" => 152, "name" => "Long BHD Fr. 25 - Fr. 29 (P. C & S)", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 156, "level" => "3", "parent_task_id" => 152, "name" => "Bottom Fr. 25 - Fr. 29", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 157, "level" => "3", "parent_task_id" => 152, "name" => "Side Shell Fr. 25 - Fr. 29", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 158, "level" => "2", "parent_task_id" => 67, "name" => "SKEG", "weight" => "0.60", "sub_tasks_count" => "2", "sub_tasks_weight_sum" => "0.60"],
    ["id" => 159, "level" => "3", "parent_task_id" => 158, "name" => "Port Skeg", "weight" => "0.30", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 160, "level" => "3", "parent_task_id" => 158, "name" => "Stbd Skeg", "weight" => "0.30", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 161, "level" => "2", "parent_task_id" => 67, "name" => "SIDE BOARD", "weight" => "3.80", "sub_tasks_count" => "4", "sub_tasks_weight_sum" => "3.80"],
    ["id" => 162, "level" => "3", "parent_task_id" => 161, "name" => "AFT Sideboard", "weight" => "0.70", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 163, "level" => "3", "parent_task_id" => 161, "name" => "PORT Sideboard", "weight" => "1.20", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 164, "level" => "3", "parent_task_id" => 161, "name" => "STBD Sideboard", "weight" => "1.20", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 165, "level" => "3", "parent_task_id" => 161, "name" => "FWD Sideboard", "weight" => "0.70", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 166, "level" => "2", "parent_task_id" => 67, "name" => "BOX FENDER", "weight" => "1.20", "sub_tasks_count" => "4", "sub_tasks_weight_sum" => "1.20"],
    ["id" => 167, "level" => "3", "parent_task_id" => 166, "name" => "Box Fender AFT Port", "weight" => "0.30", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 168, "level" => "3", "parent_task_id" => 166, "name" => "Box Fender AFT STBD", "weight" => "0.30", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 169, "level" => "3", "parent_task_id" => 166, "name" => "Box Fender FWD Port", "weight" => "0.30", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 170, "level" => "3", "parent_task_id" => 166, "name" => "Box Fender FWD STBD", "weight" => "0.30", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 171, "level" => "2", "parent_task_id" => 67, "name" => "STANCHION", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 172, "level" => "2", "parent_task_id" => 67, "name" => "CHINE", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 173, "level" => "2", "parent_task_id" => 67, "name" => "GUNWALE", "weight" => "1.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 174, "level" => "2", "parent_task_id" => 67, "name" => "WINCH HOUSE", "weight" => "0.30", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 175, "level" => "2", "parent_task_id" => 67, "name" => "CHAIN LOCKER", "weight" => "0.30", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 176, "level" => "2", "parent_task_id" => 67, "name" => "ANCHOR SEATING", "weight" => "0.30", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 177, "level" => "1", "parent_task_id" => null, "name" => "Outfit", "weight" => "30.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 178, "level" => "2", "parent_task_id" => 67, "name" => "Bollards", "weight" => "10.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 179, "level" => "2", "parent_task_id" => 67, "name" => "Sideboard Door", "weight" => "10.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 180, "level" => "2", "parent_task_id" => 67, "name" => "Manhole", "weight" => "15.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 181, "level" => "2", "parent_task_id" => 67, "name" => "Eye Lug Tyre Fender & Tyre Fender", "weight" => "15.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 182, "level" => "2", "parent_task_id" => 67, "name" => "Navigation Light Brackets", "weight" => "5.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 183, "level" => "2", "parent_task_id" => 67, "name" => "Vertical Ladder", "weight" => "15.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 184, "level" => "2", "parent_task_id" => 67, "name" => "Hull Marking ", "weight" => "8.0", "sub_tasks_count" => "4", "sub_tasks_weight_sum" => "8.00"],
    ["id" => 185, "level" => "3", "parent_task_id" => 184, "name" => "a. Ship's Name", "weight" => "2.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 186, "level" => "3", "parent_task_id" => 184, "name" => "b. Load Line Mark", "weight" => "2.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 187, "level" => "3", "parent_task_id" => 184, "name" => "c. Draft Mark", "weight" => "2.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 188, "level" => "3", "parent_task_id" => 184, "name" => "d. Plimsol Mark", "weight" => "2.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 189, "level" => "2", "parent_task_id" => 67, "name" => "Towing Bracket", "weight" => "5.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 190, "level" => "2", "parent_task_id" => 67, "name" => "Winch Foundation", "weight" => "5.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 191, "level" => "2", "parent_task_id" => 67, "name" => "Bulwark", "weight" => "5.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 192, "level" => "2", "parent_task_id" => 67, "name" => "Zinc Anode", "weight" => "5.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 193, "level" => "2", "parent_task_id" => 67, "name" => "Running test Achor Windlass", "weight" => "2.0", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 194, "level" => "1", "parent_task_id" => null, "name" => "Painting", "weight" => "30.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 195, "level" => "2", "parent_task_id" => 67, "name" => "ROW MATERIAL", "weight" => "5.00", "sub_tasks_count" => "1", "sub_tasks_weight_sum" => "5.00"],
    ["id" => 196, "level" => "3", "parent_task_id" => 195, "name" => "Blasting & ShopPrimer Coat for row material", "weight" => "5.00", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 197, "level" => "2", "parent_task_id" => 67, "name" => "EXTERNAL HULL", "weight" => "95.00", "sub_tasks_count" => "6", "sub_tasks_weight_sum" => "95.00"],
    ["id" => 198, "level" => "3", "parent_task_id" => 197, "name" => "a. Topside & Bulwark", "weight" => "20", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 199, "level" => "3", "parent_task_id" => 197, "name" => "b. Under Water", "weight" => "25", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 200, "level" => "3", "parent_task_id" => 197, "name" => "c. Main Deck", "weight" => "20", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 201, "level" => "3", "parent_task_id" => 197, "name" => "d. Walkway & Outfit", "weight" => "10", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 202, "level" => "3", "parent_task_id" => 197, "name" => "e. Internal Sideboard", "weight" => "10", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
    ["id" => 203, "level" => "3", "parent_task_id" => 197, "name" => "f. External Sideboard", "weight" => "10", "sub_tasks_count" => "0", "sub_tasks_weight_sum" => "0.00"],
];
